#!/usr/bin/env python3

from roku import Roku
import ssdp
import os

roku = Roku('192.168.11.103')
netflix = roku['Netflix']
plex = roku['Plex']
primevideo = roku['Prime Video']

print('...')

while True:
    actions = input()
    if(actions == "up"):
        roku.up()
    elif(actions == "down"):
        roku.down()
    elif(actions == "home"):
        roku.home()
    elif(actions == "left"):
        roku.left()
    elif(actions == "right"):
        roku.right()
    elif(actions == "select"):
        roku.select()
    elif(actions == "back"):
        roku.back()
    elif(actions == "netflix"):
        netflix.launch()
    elif(actions == "plex"):
        plex.launch()
    elif(actions == "primevideo"):
        primevideo.launch()
    else:
        print("...")
    if actions.strip() == 'exit':
        break
